{
 "title": "Electricity Price",
 "time": { "from": "now-30d", "to": "now" },
 "panels": [
  {
   "title": "Panel Title",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 24, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "currencyEUR" } },
   "targets": [
    {
     "query": "from(bucket: \"electricity_price\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"euro_per_kWh\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"price\")\r\n  |> set(key: \"_field\", value: \"Raw Price\")"
    },
    {
     "query": "from(bucket: \"electricity_price\")\r\n  |> range(start: -365d)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"euro_per_kWh\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"price\")\r\n  |> movingAverage(n: 30)\r\n  |> set(key: \"_field\", value: \"Moving Average\")"
    }
   ]
  },
  {
   "title": "Min",
   "type": "stat",
   "gridPos": { "h": 5, "w": 5, "x": 0, "y": 13 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"electricity_price\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"euro_per_kWh\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"price\")\r\n  |> min()"
    }
   ]
  },
  {
   "title": "Mean",
   "type": "stat",
   "gridPos": { "h": 5, "w": 5, "x": 9, "y": 13 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"electricity_price\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"euro_per_kWh\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"price\")\r\n  |> mean()"
    }
   ]
  },
  {
   "title": "Max",
   "type": "stat",
   "gridPos": { "h": 5, "w": 5, "x": 19, "y": 13 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"electricity_price\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"euro_per_kWh\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"price\")\r\n  |> max()"
    }
   ]
  }
 ]
}